services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
      - ./backend/src/reports:/app/src/reports
    depends_on:
      - mlflow
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

  mlflow:
    build: ./mlflow
    command: server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns
    volumes:
      - ./backend/mlruns:/mlflow/mlruns
      - ./backend/mlflow.db:/mlflow/mlflow.db
    ports:
      - "5000:5000"
    networks:
      - app-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: automl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: