services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/models:/app/models
      - ./backend/src/reports:/app/src/reports
    depends_on:
      - mlflow
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  mlflow:
    build: ./mlflow
    command: server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns
    volumes:
      - ./backend/mlruns:/mlflow/mlruns
      - ./backend/mlflow.db:/mlflow/mlflow.db
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network: